version: "3.7"

# This compose file isn't optimized for local development
# only for running it in dev mode on your local machine without much fuzz
services:

  lame_recipes:
    container_name: lame_recipes
    build:
      context: .
    environment:
      - PORT=5000
      - NODE_ENV=development
      - IS_HTTPS_ACTIVE=false
      - ENABLE_DB_LOGGING=true
    volumes:
      - ./uploads:/app/backend/uploads
      - ./db:/app/backend/db
    ports:
      - "5000:5000"