name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@master
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build . -t brunojppb/lame_recipes:latest
      - name: docker push
        run: |
          docker push brunojppb/lame_recipes:latest
  deploy:
    name: Deploy new image on server
    runs-on: ubuntu-latest
    needs: [build]
    env:
      SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
    steps:
      - uses: actions/checkout@master
      - name: prepare docker
        run: |
          mkdir -p ~/.ssh
          echo "${SERVER_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
      - name: deploy docker image
        run: |
          ssh root@$SERVER_IP "mkdir -p lame_recipes"
          scp -r ./docker-compose.prod.yml root@$SERVER_IP:~/lame_recipes/docker-compose.yml
          ssh root@$SERVER_IP << ENDSSH
            cd lame_recipes
            # This is running in a very cheap VPS on Hetzner
            # So not a lot of disk space around to hold unused docker images
            docker system prune --all --force
            docker-compose pull lame_recipes
            docker-compose down
            docker-compose up -d
          ENDSSH